<a href="https://colab.research.google.com/github/API-GPI-Grupo-3-Automotiva/Projeto-Integrador-II/blob/main/DADOS_RAIS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DADOS DA RAIS

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
origem = '/content/drive/MyDrive/Data/RAIS/'

In [ ]:
file_1 = origem + 'RAIS_ESTAB_PUB.txt'
rais24 = pd.read_csv(file_1,low_memory=False,sep =';',encoding = 'latin1')

In [ ]:
file_2 = origem + 'diretorio_uf_brasil.csv'
UF = pd.read_csv(file_2,low_memory=False,sep =';',encoding ='latin1')

In [ ]:
rais24.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12643067 entries, 0 to 12643066
Data columns (total 24 columns):
 #   Column                     Dtype
---  ------                     -----
 0   Bairros SP                 int64
 1   Bairros Fortaleza          int64
 2   Bairros RJ                 int64
 3   CNAE 2.0 Classe            int64
 4   CNAE 95 Classe             int64
 5   Distritos SP               int64
 6   Qtd Vínculos CLT           int64
 7   Qtd Vínculos Ativos        int64
 8   Qtd Vínculos Estatutários  int64
 9   Ind Atividade Ano          int64
 10  Ind CEI Vinculado          int64
 11  Ind Estab Participa PAT    int64
 12  Ind Rais Negativa          int64
 13  Ind Simples                int64
 14  Município                  int64
 15  Natureza Jurídica          int64
 16  Regiões Adm DF             int64
 17  CNAE 2.0 Subclasse         int64
 18  Tamanho Estabelecimento    int64
 19  Tipo Estab                 int64
 20  Tipo Estab.1               object
 21  UF                         object
 22  IBGE Subsetor              int64
 23  CEP Estab                  int64
dtypes: int64(22), object(2)
memory usage: 2.3+ GB

In [ ]:
UF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Codigo_UF    27 non-null     int64
 1   UF           27 non-null     object
 2   Nome_Estado  27 non-null     object
 3   Região       27 non-null     object
dtypes: int64(1), object(3)
memory usage: 996.0+ bytes

In [ ]:
UF.head()

   Codigo_UF  UF Nome_Estado Região
0         11  RO    Rondônia  Norte
1         12  AC        Acre  Norte
2         13  AM    Amazonas  Norte
3         14  RR     Roraima  Norte
4         15  PA        Pará  Norte

In [ ]:
UF[UF['UF']=='SP']

    Codigo_UF  UF Nome_Estado   Região
19         35  SP   São Paulo  Sudeste

In [ ]:
rais24['UF'].unique()

array(['11', '12', '13', '14', '15', '16', '17', '21', '22', '23', '24',
       '25', '26', '27', '28', '29', '31', '32', '33', '35', '41', '42',
       '43', '50', '51', '52', '53', '{ñ'], dtype=object)

In [ ]:
rais_final = rais24[rais24['UF'] == '35']
rais_final = rais_final.reset_index(drop=True)

In [ ]:
rais_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3157330 entries, 0 to 3157329
Data columns (total 24 columns):
 #   Column                     Dtype
---  ------                     -----
 0   Bairros SP                 int64
 1   Bairros Fortaleza          int64
 2   Bairros RJ                 int64
 3   CNAE 2.0 Classe            int64
 4   CNAE 95 Classe             int64
 5   Distritos SP               int64
 6   Qtd Vínculos CLT           int64
 7   Qtd Vínculos Ativos        int64
 8   Qtd Vínculos Estatutários  int64
 9   Ind Atividade Ano          int64
 10  Ind CEI Vinculado          int64
 11  Ind Estab Participa PAT    int64
 12  Ind Rais Negativa          int64
 13  Ind Simples                int64
 14  Município                  int64
 15  Natureza Jurídica          int64
 16  Regiões Adm DF             int64
 17  CNAE 2.0 Subclasse         int64
 18  Tamanho Estabelecimento    int64
 19  Tipo Estab                 int64
 20  Tipo Estab.1               object
 21  UF                         object
 22  IBGE Subsetor              int64
 23  CEP Estab                  int64
dtypes: int64(22), object(2)
memory usage: 578.1+ MB

In [ ]:
rais_final.to_csv(origem + 'rais_final.csv', index=False)